const DEFAULT_INTERVAL_SECONDS = 60;
const DEFAULT_REQUEST_TIMEOUT_SECONDS = 30;
const MAX_TEST_HISTORY_ITEMS = 24;

module.exports = {
  DEFAULT_INTERVAL_SECONDS,
  DEFAULT_REQUEST_TIMEOUT_SECONDS,
  MAX_TEST_HISTORY_ITEMS,
};
